import type { Metadata } from "next";
import { Chivo_Mono } from "next/font/google";
import { PlaybackControls } from "./components/PlaybackControls";
import { Sidebar } from "./components/Sidebar";
import "./globals.css";

const chivoMono = Chivo_Mono({
  variable: "--font-chivo-Mono",
  weight: "variable",
  style: ["normal"],
  subsets: ["latin"],
  display: "swap",
  fallback: ["sans-serif"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${chivoMono.className} antialiased`}>
        <div className="flex h-full">
          <Sidebar />
          <div className="flex flex-1 flex-col p-6">
            {children}
            <PlaybackControls />
          </div>
        </div>
      </body>
    </html>
  );
}
